// <auto-generated />
namespace LMS.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Sync_DriverFlow_Models : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sync_DriverFlow_Models));
        
        string IMigrationMetadata.Id
        {
            get { return "202510230813208_Sync_DriverFlow_Models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
